name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      - name: Build APK with Buildozer
        uses: artem-shestakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: anime_alert
          buildozer_version: master

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: anime-alert-apk
          path: ${{ steps.buildozer.outputs.filename }}
