name: Build APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (no submodules)
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build with Buildozer in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostcwd \
            -w /home/user/hostcwd/anime_alert \
            kivy/buildozer android debug
